### ISSUE TITLE
Firefox complains that example requires too much info, suspicious behavior

### ISSUE THREAD

**Issue by nekromoff** [lbuchs/WebAuthn#14]
![image](https://user-images.githubusercontent.com/8550349/72834576-691e4900-3c89-11ea-8070-ea8edb610120.png)

This other library does not have this issue:
https://github.com/davidearl/webauthn

**Comment by Spomky** [comment]
This is not an issue but the normal behaviour of Firefox when the Authenticator Attestation is asked.

In the demo, if you only check the attestation statement format `none` (i.e. no attestation is asked), you won't receive any warning
If you check any other attestation statement format than `none`, an authenticator attestation is asked and you receive this alert.

This does not prevent the registration to be performed.

Ref: https://github.com/lbuchs/WebAuthn/blob/master/WebAuthn.php#L146

**Comment by nekromoff** [comment]
Alright, thank you for the explanation. It just is somehow suspicious if
such a message is displayed for a user.

**Comment by My1** [comment]
well chrome does this too as far as I remember and a user can either just go and block the attestation passthrough or let it through when this happens and you can choose what to do upon that.

on the other hand as said above, just select none only and no one will complain.
but this attestation info can be useful for example if you are in an environment where users only get certain Fido devices anyway but should self enroll due to it being easier that way, then you can force the attestation server side and only let keys of this kind through like for example only valid Yubikeys or Secure Solos or whatever.

also if you know even roughly what model of a security key a user has you can inform them when security problems occur or whatever.

but in most normal scenarios you shouldnt force users to send attestation and just have them register a name for their device so they can distinguish them later. but having it optionally enabled isnt too bad if you ask me. (even though not storing attestations and stuff can save a bit of database space (albeit not a lot if the database is smart enough not to store duplicates unnesecarily.
